.PHONY: all clean

all:
	-mkdir clients_out clients_err_out server_out server_err_out downloaded_files rejected_files
clean:
	-rm -fR clients_out clients_err_out server_out server_err_out downloaded_files rejected_files
test1:
	./test1.sh
test2:
	./test2.sh
test3:
	./test3.sh